services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_base_app
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor/
      - ./storage:/var/www/storage/
      - ./bootstrap/cache:/var/www/bootstrap/cache/
      - .env:/var/www/.env
    ports:
      - "8000:80"
      - "9000:9000"
    networks:
      - lb_network

  mysql:
    image: mysql:8.4.4
    container_name: laravel_base_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lb_network
volumes:
  mysql_data:
networks:
  lb_network:
    driver: bridge
