services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_base_app
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor/
      - ./storage:/var/www/storage/
      - ./bootstrap/cache:/var/www/bootstrap/cache/
      - .env:/var/www/.env
      - ./docker/supervisor/supervisord.conf:/etc/supervisord.conf
      - ./docker/supervisor/conf.d:/etc/supervisor/conf.d
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - "9000:9000"
    networks:
      - lb_network
    depends_on:
      - mysql

  nginx:
    image: nginx:1.27.4-alpine
    container_name: laravel_base_nginx
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/nginx/http.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - lb_network
    depends_on:
      - app

  mysql:
    image: mysql:8.4.4
    container_name: laravel_base_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lb_network

  redis:
    image: redis:7.2.4
    container_name: laravel_base_redis
    restart: unless-stopped
    environment:
      #- REDIS_USER=default mặc định nó là user default
      - REDIS_PASSWORD=admin
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--requirepass", "admin", "--appendonly", "yes" ]
    networks:
      - lb_network

volumes:
  mysql_data:
  redis_data:
networks:
  lb_network:
    driver: bridge
